// Official local brand assets used by provider cards and model rows.
// Keep every returned path inside public/ and make the fallback an actual
// checked-in SVG so an upstream typo can never produce a broken image.

export const MODEL_ICON_FALLBACK = '/model-icons/default.svg';

export const PROVIDER_LOGO_MAP = Object.freeze({
  // Core / first-party providers
  nvidia: '/logos/nvidia.svg',
  google: '/logos/google.svg',
  gemini: '/logos/gemini.svg',
  'gemini-cli': '/provider-logos/gemini-cli.svg',
  openai: '/logos/openai.svg',
  'openai-codex': '/logos/openai-codex.svg',
  anthropic: '/logos/anthropic.svg',
  deepseek: '/logos/deepseek.svg',
  mistral: '/logos/mistral.svg',
  meta: '/logos/meta.svg',
  qwen: '/logos/qwen.svg',
  'qwen-cloud': '/logos/qwen-cloud.svg',
  groq: '/logos/groq.svg',
  cohere: '/logos/cohere.svg',
  xai: '/logos/xai.svg',
  cerebras: '/provider-logos/cerebras.svg',
  together: '/provider-logos/together.svg',
  microsoft: '/model-icons/microsoft.svg',
  huggingface: '/logos/huggingface.svg',
  replicate: '/logos/replicate.svg',
  perplexity: '/logos/perplexity.svg',
  writer: '/logos/writer.svg',
  databricks: '/logos/databricks.svg',
  snowflake: '/logos/snowflake.svg',
  ai21: '/provider-logos/ai21.svg',
  aisingapore: '/logos/aisingapore.png',
  bigcode: '/logos/bigcode.svg',
  poolside: '/logos/poolside.svg',
  moonshot: '/logos/moonshot.svg',
  kimi: '/provider-logos/kimi.svg',
  zai: '/logos/zai.svg',
  zhipu: '/logos/zhipu.svg',
  gemma: '/logos/gemma.svg',
  stability: '/model-icons/stability.svg',
  deepgram: '/logos/deepgram.svg',
  elevenlabs: '/logos/elevenlabs.svg',
  jina: '/logos/jina.svg',
  'jina-ai': '/logos/jina-ai.svg',
  upstage: '/logos/upstage.svg',
  morph: '/logos/morph.svg',
  typhoon: '/logos/typhoon.svg',
  wandb: '/logos/wandb.png',

  // Cloud, router and ecosystem providers. These are real local marks, not
  // generated placeholders; aliases below cover the ids used by the gateway.
  cloudflare: '/logos/cloudflare-ai.svg',
  'cloudflare-ai': '/logos/cloudflare-ai.svg',
  cloudflareai: '/logos/cloudflare-ai.svg',
  cf: '/logos/cf.svg',
  openrouter: '/logos/openrouter.svg',
  ollama: '/logos/ollama-cloud.svg',
  'ollama-cloud': '/logos/ollama-cloud.svg',
  ollamacloud: '/logos/ollama-cloud.svg',
  alibaba: '/logos/alibaba.svg',
  ali: '/logos/ali.svg',
  qwc: '/logos/qwc.svg',
  searchapi: '/logos/searchapi.svg',
  'searchapi-search': '/logos/searchapi-search.svg',
  context7: '/logos/context7.png',
  linkup: '/logos/linkup.svg',
  'linkup-search': '/logos/linkup-search.svg',
  youcom: '/logos/youcom.svg',
  'youcom-search': '/logos/youcom-search.svg',
  vertexai: '/provider-logos/vertexai.svg',
  bedrock: '/provider-logos/bedrock.svg',
  azure: '/provider-logos/azure.svg',
  aws: '/provider-logos/aws.svg',
  fireworks: '/provider-logos/fireworks.svg',
  sambanova: '/provider-logos/sambanova.svg',
  deepinfra: '/provider-logos/deepinfra.svg',
  vllm: '/provider-logos/vllm.svg',
  leptonai: '/provider-logos/leptonai.svg',
  novita: '/provider-logos/novita.svg',
  stepfun: '/provider-logos/stepfun.svg',
  modelscope: '/provider-logos/modelscope.svg',
  siliconflow: '/provider-logos/siliconflow.svg',
  sensenova: '/provider-logos/sensenova.svg',
  spark: '/provider-logos/spark.svg',
  doubao: '/provider-logos/doubao.svg',
  hailuo: '/provider-logos/hailuo.svg',
  hunyuan: '/provider-logos/hunyuan.svg',
  chatglm: '/provider-logos/chatglm.svg',
  internlm: '/provider-logos/internlm.svg',
  lingyiwanwu: '/provider-logos/lingyiwanwu.svg',
  baichuan: '/provider-logos/baichuan.svg',
  'baichuan-ai': '/provider-logos/baichuan-ai.svg',
  minimax: '/provider-logos/minimax.svg',
  yi: '/provider-logos/yi.svg',
  zeroone: '/provider-logos/zeroone.svg',
  arcee: '/provider-logos/arcee.svg',
  jinaai: '/logos/jina-ai.svg',

  // Local catalogue/router ids
  agnes: '/logos/agnes.svg',
  agy: '/logos/agy.svg',
  aichixia: '/logos/aichixia.svg',
  aifree: '/logos/aifree.svg',
  aion: '/logos/aion.svg',
  amanai: '/logos/amanai.svg',
  apmix: '/logos/apmix.svg',
  aquadevs: '/logos/aquadevs.svg',
  auriko: '/logos/auriko.svg',
  auto: '/logos/auto.svg',
  bai: '/logos/bai.svg',
  bazaarlink: '/logos/bazaarlink.svg',
  blazeapi: '/logos/blazeapi.svg',
  bynara: '/logos/bynara.svg',
  bzl: '/logos/bzl.svg',
  charm: '/logos/charm-hyper.svg',
  'charm-hyper': '/logos/charm-hyper.svg',
  codecraft: '/logos/codecraft.svg',
  crax: '/logos/crax.svg',
  craxbackup: '/logos/crax_backup.svg',
  'crax-backup': '/logos/crax_backup.svg',
  customomniroute: '/logos/other.svg',
  dahl: '/logos/dahl.svg',
  drd: '/logos/drd.svg',
  electronhub: '/logos/electronhub.svg',
  evolvex: '/logos/evolvex.svg',
  fastrouter: '/logos/fastrouter.svg',
  faucet: '/logos/faucet.svg',
  freeai: '/logos/free-ai.svg',
  'free-ai': '/logos/free-ai.svg',
  freee: '/logos/freee.svg',
  freetheai: '/logos/freetheai.svg',
  gonka: '/logos/gonka.svg',
  hallo: '/logos/hallo.svg',
  hcn: '/logos/hcn.svg',
  inception: '/logos/inception.svg',
  kc: '/logos/kc.svg',
  kenari: '/logos/kenari.svg',
  kg: '/logos/kg.svg',
  kilocode: '/logos/kilocode.svg',
  kilogateway: '/logos/kilo-gateway.svg',
  'kilo-gateway': '/logos/kilo-gateway.svg',
  literouter: '/logos/literouter.svg',
  llm7: '/logos/llm7.svg',
  llmkiwi: '/logos/llmkiwi.svg',
  'llm-kiwi': '/logos/llm-kiwi.svg',
  logfare: '/logos/logfare.svg',
  nothink: '/logos/no-think.svg',
  'no-think': '/logos/no-think.svg',
  oad: '/logos/oad.svg',
  ollamacloud: '/logos/ollama-cloud.svg',
  omniroute: '/logos/other.svg',
  openadapter: '/logos/openadapter.svg',
  openagentic: '/logos/openagentic.svg',
  opencodezen: '/logos/opencode-zen.svg',
  'opencode-zen': '/logos/opencode-zen.svg',
  osaii: '/logos/osaii.svg',
  other: '/logos/other.svg',
  paxsenix: '/logos/paxsenix.svg',
  routeway: '/logos/routeway.svg',
  routmy: '/logos/routmy.svg',
  rsiai: '/logos/rsiai.svg',
  tokenharbor: '/logos/tokenharbor.svg',
  tokenreply: '/logos/tokenreply.svg',
  tokenrouter: '/logos/token-router.svg',
  'token-router': '/logos/token-router.svg',
  unikey: '/logos/unikey.svg',
  zhipu: '/logos/zhipu.svg',
});

const MODEL_RULES = [
  // Specific model families first: these are model marks, not their route.
  ['stable-diffusion', '/model-icons/stability.svg'],
  ['flux', '/model-icons/flux.svg'],
  ['pixtral', '/model-icons/pixtral.svg'],
  ['codestral', '/model-icons/codestral.svg'],
  ['ministral', '/model-icons/ministraux.svg'],
  ['mistral', '/model-icons/mistral.svg'],
  ['devstral', '/model-icons/mistral.svg'],
  ['magistral', '/model-icons/magistral.svg'],
  ['voxtral', '/model-icons/voxtral.svg'],
  ['deepseek', '/model-icons/deepseek.svg'],
  ['qwen', '/model-icons/qwen.svg'],
  ['qwq', '/model-icons/qwen.svg'],
  ['llama', '/model-icons/llama.svg'],
  ['meta-llama', '/model-icons/llama.svg'],
  ['gemma', '/model-icons/gemma.svg'],
  ['gemini', '/model-icons/gemini.svg'],
  ['imagen', '/model-icons/gemini.svg'],
  ['veo', '/model-icons/gemini.svg'],
  ['lyria', '/model-icons/gemini.svg'],
  ['claude', '/model-icons/claude.svg'],
  ['anthropic', '/model-icons/claude.svg'],
  ['sonnet', '/model-icons/claude.svg'],
  ['opus', '/model-icons/claude.svg'],
  ['haiku', '/model-icons/claude.svg'],
  ['granite', '/model-icons/granite.svg'],
  ['ibm/', '/model-icons/granite.svg'],
  ['phi-', '/model-icons/microsoft.svg'],
  ['microsoft', '/model-icons/microsoft.svg'],
  ['bitnet', '/model-icons/bitnet.svg'],
  ['gpt', '/model-icons/gpt.svg'],
  ['openai', '/model-icons/gpt.svg'],
  ['codex', '/model-icons/codex.svg'],
  ['whisper', '/model-icons/whisper.svg'],
  ['sora', '/model-icons/sora.svg'],
  ['dall', '/model-icons/gpt.svg'],
  ['command', '/model-icons/commanda.svg'],
  ['cohere', '/model-icons/cohere.svg'],
  ['aya', '/model-icons/aya.svg'],
  ['jamba', '/model-icons/ai21.svg'],
  ['ai21', '/model-icons/ai21.svg'],
  ['kimi', '/model-icons/kimi.svg'],
  ['moonshot', '/model-icons/kimi.svg'],
  ['glm', '/model-icons/glm.svg'],
  ['zai', '/model-icons/zai.svg'],
  ['yi-', '/model-icons/yi.svg'],
  ['01-ai', '/model-icons/yi.svg'],
  ['dbrx', '/model-icons/dbrx.svg'],
  ['databricks', '/model-icons/dbrx.svg'],
  ['nemotron', '/model-icons/nemotron.svg'],
  ['parakeet', '/model-icons/parakeet.svg'],
  ['minimax', '/model-icons/minimax.svg'],
  ['hunyuan', '/model-icons/hunyuan.svg'],
  ['doubao', '/model-icons/doubao.svg'],
  ['seed', '/model-icons/seed.svg'],
  ['internlm', '/model-icons/internlm.svg'],
  ['poolside', '/model-icons/poolside.svg'],
  ['morph', '/model-icons/morph.svg'],
  ['typhoon', '/model-icons/typhoon.svg'],
  ['upstage', '/model-icons/upstage.svg'],
  ['solar', '/model-icons/solar.svg'],
  ['grok', '/model-icons/grok.svg'],
  ['nova', '/model-icons/nova.svg'],
  ['amazon', '/model-icons/nova.svg'],
  ['cloudflare', '/model-icons/cloudflare.svg'],
  ['apertus', '/model-icons/apertus.svg'],
  ['sensenova', '/provider-logos/sensenova.svg'],
  ['baidu', '/model-icons/baidu.svg'],
  ['ernie', '/model-icons/baidu.svg'],
  ['tencent', '/model-icons/tencent.svg'],
  ['sarvam', '/model-icons/sarvam.svg'],
  ['mimo', '/model-icons/mimo.svg'],
  ['xiaomi', '/model-icons/mimo.svg'],
  ['longcat', '/model-icons/longcat.svg'],
  ['meituan', '/model-icons/longcat.svg'],
  ['venice', '/model-icons/venice.svg'],
  ['happyhorse', '/model-icons/happyhorse.svg'],
  ['starcoder', '/logos/bigcode.svg'],
  ['bigcode', '/logos/bigcode.svg'],
  ['zyphra', '/logos/zyphra.png'],
  ['perplexity', '/logos/perplexity.svg'],
  ['sonar', '/logos/perplexity.svg'],
  ['huggingface', '/logos/huggingface.svg'],
  ['writer', '/logos/writer.svg'],
  ['palmyra', '/logos/writer.svg'],
  ['snowflake', '/logos/snowflake.svg'],
  ['arctic', '/logos/snowflake.svg'],
];

const ROUTER_WORDS = new Set([
  'auto', 'best', 'free', 'cheap', 'fast', 'faster', 'ultrafast', 'thrifty',
  'smart', 'coding', 'chat', 'vision', 'reasoning', 'multimodal', 'offline',
  'chaos', 'demo', 'pro', 'space', 'subscription',
]);

function normalizeId(value) {
  return String(value ?? '').trim().toLowerCase();
}

/** Return a local official provider mark, never null for a provider card. */
export function getProviderLogo(providerId = '') {
  const pid = normalizeId(providerId);
  const direct = PROVIDER_LOGO_MAP[pid] || PROVIDER_LOGO_MAP[pid.replace(/[_\s]+/g, '-')];
  if (direct) return direct;

  const prefix = pid.split('/')[0].replace(/[_\s]+/g, '-');
  if (PROVIDER_LOGO_MAP[prefix]) return PROVIDER_LOGO_MAP[prefix];

  // A few gateway ids omit punctuation entirely.
  const compact = pid.replace(/[-_\s]/g, '');
  const compactAlias = {
    cloudflareai: 'cloudflare-ai',
    jinaai: 'jina-ai',
    openaicodex: 'openai-codex',
    opencodezen: 'opencode-zen',
    qwencloud: 'qwen-cloud',
    ollamacloud: 'ollama-cloud',
    kilogateway: 'kilo-gateway',
    tokenrouter: 'token-router',
  }[compact];
  return (compactAlias && PROVIDER_LOGO_MAP[compactAlias]) || PROVIDER_LOGO_MAP.other;
}

/** Return the closest local official model-family icon for a model id. */
export function getModelLogo(modelId = '') {
  const mid = normalizeId(modelId);
  const tail = mid.split('/').pop()?.split(':')[0] || '';
  if (ROUTER_WORDS.has(tail)) return MODEL_ICON_FALLBACK;

  const hit = MODEL_RULES.find(([needle]) => mid.includes(needle) || tail.includes(needle));
  if (hit) return hit[1];

  // NVIDIA's catalogue contains a large number of first-party NIM models;
  // use its checked-in model mark only for an explicitly NVIDIA namespace.
  if (mid.startsWith('nvidia/') || mid.includes('/nvidia/')) return '/model-icons/nvidia.svg';
  return MODEL_ICON_FALLBACK;
}
